apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: twy-prod
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "520153421142"
    project: twy-website-analytics
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: twygmbh
    repository: kubernetes-production
  - key: staging
  - key: production
  ingress:
    domain: prod.twy.gmbh
    externalDNS: true
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: reto@twy.gmbh
      enabled: true
      production: true
  kuberhealthy: true
  pipelineUser:
    username: lukso-k8s-bot
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-twy-prod-e7ab7445c061
  - name: reports
    url: gs://reports-twy-prod-e7ab7445c061
  - name: repository
    url: gs://repository-twy-prod-e7ab7445c061
  vault: {}
  webhook: lighthouse
